# Generated by Django 5.2.5 on 2025-08-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_academicsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
