# Generated by Django 5.2.5 on 2025-08-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_faculty_department_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='short',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
