# Generated by Django 5.2.5 on 2025-08-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='api.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='api.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='api.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='api.studentprofile')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'unique_together': {('student', 'course', 'academic_session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('semester_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='api.academicsession')),
                ('courses', models.ManyToManyField(blank=True, related_name='course_registrations', to='api.courseenrollment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='api.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='api.studentprofile')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'academic_session', 'semester')},
            },
        ),
    ]
