# Generated by Django 5.2.5 on 2025-08-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_courseenrollment_courseregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, help_text='Level for which this course is intended (e.g., 100, 200, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.level'),
        ),
    ]
