# Generated by Django 5.2.5 on 2025-08-22 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_level_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.level'),
        ),
    ]
