# Generated by Django 5.2.5 on 2025-09-23 10:40

import api.models.lecturer
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_studentprofile_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.CharField(default=api.models.lecturer.generate_lecturer_id, max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_lecturers',
            field=models.ManyToManyField(blank=True, help_text='Lecturers assigned to teach this course', related_name='assigned_courses', to='api.lecturerprofile'),
        ),
    ]
