# Generated by Django 5.2.5 on 2025-10-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text='Head of Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of_department', to='api.lecturerprofile'),
        ),
    ]
