# Generated by Django 5.2.5 on 2025-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='borrowing_departments',
            field=models.ManyToManyField(blank=True, help_text='Other departments that can register students for this course', related_name='borrowed_courses', to='api.department'),
        ),
    ]
