# Generated by Django 5.2.5 on 2025-11-13 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_course_borrowing_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_general', models.BooleanField(default=False, help_text='True for general announcements, False for course-specific')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for general announcements', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to='api.lecturerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
